# Generated by Django 4.1.5 on 2023-01-10 23:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500, null=True)),
                ('date_start', models.DateTimeField(default=datetime.datetime.now)),
                ('date_end', models.DateTimeField()),
                ('progress_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'InProgress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Pending', max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
