# Generated by Django 4.1.5 on 2023-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoListApp', '0003_alter_task_date_end_alter_task_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to='tasks_files'),
        ),
    ]
