# Generated by Django 4.1.5 on 2023-01-10 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)[A-Za-z\\d]{8,}$', message='Username must contain at least 8 characters, including at least 1 uppercase letter, 1 lowercase letter, and 1 number')], verbose_name='Username')),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*])(?=.*\\d)[A-Za-z\\d!@#$%^&*]{8,}$', message='Password must contain at least 8 characters, including at least 1 uppercase letter, 1 lowercase letter, 1 special character, and 1 number')], verbose_name='Password')),
                ('full_name', models.CharField(max_length=250, verbose_name='Complete Name')),
                ('profile_photo', models.ImageField(null=True, upload_to='users', verbose_name='Photo de profil')),
                ('is_valid', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
