# Generated by Django 4.1.5 on 2023-01-10 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*])(?=.*\\d)[A-Za-z\\d!@#$%^&*]{8,}$', message='Password must contain at least 8 characters, including at least 1 uppercase letter, 1 lowercase letter, 1 special character, and 1 number')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Complete Name'),
        ),
    ]
