# Generated by Django 4.1.5 on 2023-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_re_password_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='re_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
